### ISSUE TITLE
list orders pagination error

### ISSUE THREAD

**Issue by hegusung** [danpaquin/gdax-python#180]
There is still an error I didn't noticed before my merge request :
gdax/authenticated_client.py line 133

`self.paginate_orders(product_id, result, r.headers['cb-after'])`
should be
`self.paginate_orders(product_id, status, result, r.headers['cb-after'])`

sorry about that...

**Comment by skyl** [comment]
```
TypeError: paginate_orders() missing 1 required positional argument: 'after'
```

?

**Comment by jackusc** [comment]
this is due to the recursive function call not including the "status' variable when being called.  I fixed this and an ascii-encoding issue when using this on a linux system in the fork i submitted.  You can pull the authenticated_client.py file and public_client.py file from my fork and embed them into this egg.  Or hopefully dan can do that and update the master branch
