### ISSUE TITLE
Cannot Subscribe to 'user' Websocket Channel

### ISSUE THREAD

**Issue by Vacant0mens** [danpaquin/gdax-python#205]
I have this simple test module, but I get no output when I run it, and definitely no 'Subscribed' message.
```
import json
from gdax.authenticated_client import AuthenticatedClient
from gdax.websocket_client import WebsocketClient
from config import COIN as product_id, API_KEY as api_key, \
API_SECRET as api_secret, API_PASSWORD as api_password

class WebsocketTest(WebsocketClient):
    """test websocket connection"""
    def __init__(self):
        super().__init__(products=product_id,
                         channels=['user'],
                         auth=True, api_key=api_key,
                         api_secret=api_secret,
                         api_passphrase=api_password)
        print('Starting test...')

    def on_message(message):
        print(message)

WebsocketTest()
```

**Comment by smalbadger** [comment]
I believe you need the word "self" in front of "message" in the method declaration.
->   def on_message(self, message)   instead of   def on_message(message)

Hope this helps! Did you ever get the following error?
TypeError: __init__() got an unexpected keyword argument 'channels'

I get this if I try to pass in any parameters other than products. I'll probably just start a new post if you haven't seen it.

**Comment by CreaoticX** [comment]
My guess is that you installed with pip and my comments in #208 are your problem because the version on pip supports neither different channels nor authorization.  Not sure why you didn't at least subscribe though.  When I ran it not in authorization mode it just subscribed me to the full channel.

**Comment by Vacant0mens** [comment]
@smalbadger adding `self` didn't help. same result. It prints `'Starting test...'` and then the program finishes.

@CreaoticX  I'm using the `master` version from github as of a few weeks ago. When was the last commit?

**Comment by CreaoticX** [comment]
Yeah, that's the version I used.  Trying doing one of the unauthenticated channels first.  That will confirm the rest of your code is fine.  Then my guess is that maybe you need to add the authentication headers.  I don't have an account so I can't test or confirm how to do this, but the docs say that websockets have to be authenticated the same as REST calls.  You can see an example of how they do that here.

https://docs.gdax.com/?python#signing-a-message

**Comment by Vacant0mens** [comment]
trying the  'level2' channel didn't work. am i supposed to change it to `auth=False` for that?

**Comment by smalbadger** [comment]
@Vacant0mens sorry adding self didn't work. I tried what @CreaoticX suggested and got it to work. Here's what my code looks like:


`class BotSocket(gdax.WebsocketClient):
    def __init__(self, product=None, key=None, secret=None, passphrase=None, channels=None):
        super(BotSocket, self).__init__(products=product, channels=channels)

    def on_open(self):
        print("-- Starting Bot Socket --")
        self.stop = 0

    def on_message(self, msg):
        print(msg)

    def on_close(self):
        self.stop = 1
        print("-- Terminating Bot Socket --")

passphrase= "XXX"
key=        "XXX"
secret=     "XXX"
currency = ["BTC-USD", "LTC-USD", "ETH-USD", "BCH-USD"]
socket = BotSocket(product=currency, key=key, secret=secret, passphrase=passphrase, channels=["matches"])
socket.start()
sys.sleep(60)
socket.close()`

This should print something that looks like: 
{'trade_id': 23650414, 'side': 'sell', 'maker_order_id': 'cce320ff-1d8d-471d-8976-4cf4186f42fe', 'sequence': 1828857681, 'size': '0.00136567', 'price': '730.05000000', 'taker_order_id': '9dc14c67-25e2-42cb-830d-55188337d788', 'product_id': 'ETH-USD', 'type': 'match', 'time': '2017-12-29T07:32:01.386000Z'}

Note that I did not have to authenticate the actual websocket. I passed my credentials into the botsocket in case I needed to, but it turned out that it wasn't needed.

Sorry if the code doesn't work completely by copying and pasting. I took snippits of my code just to show the picture.

**Comment by obixmt** [comment]
I struggled with this exact issue also.  As @CreaoticX in [#208](https://github.com/danpaquin/gdax-python/issues/208) the solution for me was completely removing the script, (especially the .pyc compiled copies) and then updating directly from git.

I think this thread should either be combined with #208 or marked closed.

**Comment by obixmt** [comment]
@smalbadger try this, it does the exact same thing but simpler code.  The __init()__ is not necessary in the example you posted.
```
""" git-example-01.py
      Auth: obixmt
      Date: 12/31/2017
      Required:
        gdax-python 1.0.6
        Python 2.7
"""
import gdax, time

class BotSocket(gdax.WebsocketClient):
  def on_open(self):
    self.url = "wss://ws-feed.gdax.com/"
    self.products = ["BTC-USD", "LTC-USD", "ETH-USD", "BCH-USD"]
    self.message_count = 0
    self.channels = ['ticker']
    self.type = 'ticker'
    print("-- Starting Bot Socket --")

  def on_message(self, msg):
    print(msg)

  def on_close(self):
        print("-- Terminating Bot Socket --")

socket = BotSocket()
socket.start()
time.sleep(20)
socket.close()
```

**Comment by Vacant0mens** [comment]
Okay, I didn't realize that I needed to run the `.start()` method to actually get things going. Looks like it's working now. Thanks @smalbadger
