### ISSUE TITLE
inconsistent realtime orderbook

### ISSUE THREAD

**Issue by Serpens66** [danpaquin/gdax-python#80]
Hi :)

it is really difficult or maybe inpossible to have a correct orderbook with this type of websocket..
I already wrote my own solution to build an orderbook with the websocket feed, but after some time it gets inconsistent (bid > ask).

Therefore I tried now your solution.
But again after some time best bid > best ask =/
(I used your code from order_book.py, but my own websocket client, basically ws4py module)

But I still don't know if it is just our code that is not good, or if it is the websocket feed that is faulty =/

All in all I think this "changes"-websocket orderbook feed (where websocket only send changes) is rubbish for trading. Every exchange should instead send sth like best 20 bids/asks per second. This way it is always consistent...

**Comment by Serpens66** [comment]
How about writing to every exchange, that they should offer an optional ws orderbook, like the one from therocktrading:
https://api.therocktrading.com/doc/#api-websocket
"Get first 20 orderbook rows on order book changes".

This way you always have best 20 bids/asks without any problems. And usually this is enough to trade.
I already wrote to alot of exchanges, that they should add such a thing, but it seems I'm the only one requesting this...
If everyone would do this, no one would have this stupid problems anymore.
So please also write to them :)

**Comment by danpaquin** [comment]
Hello Serpens66, while I understand your issues, sometimes the websocket feed can be unreliable through GDAX and a headache to work with.  

To offer a solution for you, it doesn't sound like having instantaneous market data is important for you.  Since the GDAX API currently supports 3-5 requests per second (different for private and public endpoints), you may be able to poll the orderbook.  I would suggest you request the level two orderbook at a determined interval.  This should suit your needs.

The orderbook presented here is still under development and any use of it is up to the responsibility of the end user.  We aim to make it easier to initialize your own real time order book without any hiccups.  If you have any other questions, please let me know.
